spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: url_service
server:
  port: 3001
short_url:
  domain: localhost:3001/
counter_file:
  location: file:/home/auro/.teenyurlservice/counter.txt
redisson:
  address: redis://127.0.0.1:6379